### PR TITLE
Array support

### PR DESCRIPTION
**Pull request by arcodesec**
Hello Enrico,

I have used your library in my project to compile expressions. It works very well, but I ran into the limitation that arrays are not supported. 

I have modified the code to support that use case.

Kind regards,
Gjalt

### CODE REVIEW

**Comment by arcodesec** [comment]
Hello Enrico,

Can you publish a new version to NuGet? This way I can remove all dependencies from a private MyGet package.

Thanks in advance.

Kind regards,
Gjalt

**Comment by kendarorg** [comment]
hi gjalt!
thanks for the help!
sunday when i ll have a compiler with me ;)
enrico

On January 15, 2016 9:19:20 PM CET, Gjalt Wijma notifications@github.com wrote:

> Hello Enrico,
> 
> Can you publish a new NuGet version? This way I can remove all
> dependencies from a privat MyGet package.
> 
> Thanks in advance.
> 
> Kind regards,
> Gjalt
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kendarorg/ExpressionBuilder/pull/1#issuecomment-172079846

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kendarorg** [comment]
Added version 2.1.2 on nuget.org :dancers:  :) with array suppor! Thanks a lot!

**Comment by arcodesec** [comment]
Thanks, it works!

**Pull request merged**
